<?php

namespace App\Model;

use Illuminate\Support\Facades\Cache;

class SystemConfig extends Model
{
    protected $fillable = ['name', 'alias', 'purpose', 'data', 'status'];
    protected $hidden = ['created_by', 'updated_by', 'deleted_at', 'created_at', 'updated_at', 'ip_address'];

    public function getDataAttribute($value)
    {
        return json_decode($value, true) ?? $value;
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::saved(function () {
            Cache::forget('system_config');
        });
    }

}
